version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      SOLANA_NETWORK: "http://127.0.0.1:8899" #Change to testnet/mainnet
      CRAFT_MINT_ADDRESS: "YOUR_CRAFT_MINT_ADDRESS"
      APPLICATION_WALLET_PRIVATE_KEY: "YOUR_APPLICATION_WALLET_PRIVATE_KEY"
      TREASURY_WALLET_PUBLIC_KEY: "YOUR_TREASURY_WALLET_PUBLIC_KEY"
      EMAIL_HOST: "smtp.example.com" #Ex: smtp.gmail.com
      EMAIL_PORT: 587
      EMAIL_HOST_USER: "your_email@example.com"
      EMAIL_HOST_PASSWORD: "your_email_password"
      EMAIL_FROM_ADDRESS: "your_email@example.com"
      MARKETPLACE_FEE:.